version: '3.8'

services:
  app:
    build:
      context: .
    command: >
      sh -c "rm db.sqlite3 &&

             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata setup_survey_data.yaml &&
             python manage.py loaddata setup_filter_data.yaml &&
             python manage.py loaddata setup_catalog_data.yaml &&
             python manage.py loaddata setup_test_transient.yaml &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./env/.env.dev
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l ERROR
    volumes:
      - ./app:/app
    depends_on:
      - app
      - rabbitmq
    env_file:
      - ./env/.env.dev
  rabbitmq:
    image: rabbitmq:3.9-alpine
    ports:
      - "5672:5672"
    env_file:
      - ./env/.env.dev
  celery_beat:
    restart: always
    build:
      context: .
    command: celery -A app beat -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - app
      - rabbitmq
      - celery
    env_file:
      - ./env/.env.dev



